### ISSUE TITLE
History Viewer: View a version

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-versioned#104]
# Acceptance Criteria

 * View a single version of a record (page or otherwise)
 * Navigate beween versions in context of the [list view](https://app.zenhub.com/workspace/o/silverstripe/silverstripe-versioned/issues/37)
 * Shows the draft/publish date and the author
 * Shows readonly version of all core form fields
 * Shows a position readonly indicator (for content blocks)
 * Each view has it's own URL so it can be shared with other CMS authors

# Notes

 * Track design time against ORB-175 Pattern Library
 * Designs at https://projects.invisionapp.com/share/FJEHOLLEN#/screens/263513634_Pages_History_Tab
 * Excludes revert button, see https://app.zenhub.com/workspace/o/silverstripe/silverstripe-versioned/issues/95

## Pull requests

- [ ] #5
- [ ] https://github.com/silverstripe/silverstripe-admin/pull/490
- [ ] https://github.com/silverstripe/webpack-config/pull/19

**Comment by robbieaverill** [comment]
Status update:

* WIP branch at https://github.com/creative-commoners/silverstripe-versioned-admin/tree/pulls/1.0/detail-view
* Redux state, actions, types and reducer added for navigating between views in history viewer
* Designs implemented for detail view

Todo:

- [ ] Confirm with @clarkepaul/@sachajudd how tabs should be displayed if they exist
- [ ] Remove History tab from elemental when in the context of the history viewer
- [ ] Fix tests and write new ones

**Comment by clarkepaul** [comment]
@robbieaverill So we haven't shown the settings for history previously and I'm not sure it is versioned (I think last I heard it wasn't versioned?) obviously history tab can go. It looks like there is a double margin/padding surrounding the tabs on the left and right (should be 20px either side). Otherwise coming long good.

**Comment by robbieaverill** [comment]
@clarkepaul I've removed the history viewer field from the History tab in this example (content blocks) and then removed any empty tabs, which History is in this case.

Developers can push versioned DB fields into any number of arbitrary tabs for a DataObject, so tabbing is highly likely. Another example would be blog page types which have multiple tabs.

You're right in that for pages the Settings tab is not a real CMS tab, but it still has versioned DB fields in it.

If you have a chance next week maybe pop down and we can smash out the alignment tweaks together?

**Comment by robbieaverill** [comment]
PR up for review at https://github.com/silverstripe/silverstripe-versioned-admin/pull/5.

I expect there's a few areas that can be refactored, but this is a working/linted/unit tested version where Redux is introduced at a higher level.

@tractorcow mentioned we could probably inject the form schema URL from higher up, since the only variant at the stage it's current generated is the version number. At the moment it's adding the record's class name and ID as well.

Also need to review the redux implementation to ensure that it makes sense.
