### ISSUE TITLE
Author is a reserved word in Silverstripe Versioning, this is perhaps on overreach

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-versioned#309]
We recently versioned a bunch of DataObjects and all of a sudden the Authors did not show up in templates any longer (database works fine).  The behaviour was also very erratic (i.e. Author returned true in template, but was empty). 

This relates to:
https://github.com/silverstripe/silverstripe-versioned/blob/732d448c69effaa9eedd8a8ffb15e70a6640a7f1/src/GraphQL/Extensions/DataObjectScaffolderExtension.php#L21-L99

from what I can tell.

**Comment by sunnysideup** [comment]
I dont think this is quite right, we will investigate further.

**Comment by cwchong** [comment]
Hi @sunnysideup, I am currently seeing the same, when migrating code from v3 to v4
AFAICT, updating the line in  
https://github.com/silverstripe/silverstripe-versioned/blob/e3d67d7b2fb7ae63e914c313259914d32bb67a54/src/Versioned.php#L3079-L3087
```
    public function Author()
    {
        if ($this->owner->hasField('Author')) return $this->owner->Author; // +++
        if (!$this->owner->AuthorID) {
            return null;
        }
        /** @var Member $member */
        $member = DataObject::get_by_id(Member::class, $this->owner->AuthorID);
        return $member;
    }
```
Sort of bandages the problem, but I find it kind of dirty that the call can thus return either a string (or whatever your dbfield 'Author' is defined as) or a Member object

Interested to know what you did to fix your issue (perhaps just renaming the dbfield instead?)

Is this by design a reserved word now in v4?

**Comment by cwchong** [comment]
Alternatively the more straightforward way i can think of is to override with your own declaration of `Author()` in your dataobject/page:

```
    public function Author()
    {
        return $this->Author;
    }
```

Think this might be the 'cleanest' solution
