### ISSUE TITLE
canViewStage appears to be unused

### ISSUE THREAD

**Issue by dhensby** [silverstripe/silverstripe-versioned#46]
The method `Versioned::canViewStage()` doesn't appear to be used throughout a normal silverstripe codebase.

I'm not sure of it's purpose as it appears that `canViewVersioned` has taken over and it's implied that `Live` is always viewable and the draft site logic is then handled in the body of `canViewVersioned`

**Comment by chillu** [comment]
With `canViewStage()`, you can force permission checks for a certain stage, rather than have these implied by the current query params in `canViewVersioned()`. So I think there's still a use case for it. We can't remove it in 4.x since it's part of the public API, but even for 5.x I think some people will find it useful?

**Comment by dhensby** [comment]
Hmm - maybe I'm misunderstanding what `canViewStaged` is meant to do - I'll try to look into this again
