### ISSUE TITLE
Communicate save/publish impact to authors (when using $owns)

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-versioned#71]
# Overview

Since ownership is determined by developers in code, authors don't have any indication on what other records will be affected when saving and publishing the currently viewed one. The system allows for a mixture of versioned and non-versioned records. We need a UI that makes the author confident about the impact of save and publish operations. They want to know that any previews of the draft state will become what website visitors see once the record is published.

Split out from [Allow $owns on non-Versioned objects](https://github.com/silverstripe/silverstripe-framework/issues/7359).

# Acceptance Criteria

 * If owner is versioned but any owned relationships aren't, the button labels are "save" and "publish" (status quo)
 * If both owner and ownee are versioned, the button labels are "save" and "publish" (status quo)
 * If owner is unversioned with owned relationships, a warning will be shown
 * If owner is unversioned with owned relationships, the button label is "Apply changes"
 * If both owner and ownee are unversioned, the button label is "Apply changes"
 * The logic works with all kinds of relationships (has_one, has_many, many_many)
 * The logic works with custom relationship getters
 * The change does not significantly affect form loading or saving performance, even when the form has a dozen owns relationships with dozens of (versioned) items each

# Notes

 * Excludes listing which relationship has draft changes
 * When any user actions on the same screen lead to relationships being published or unpublished, the warning label does not need to be removed or added
 * Work might overlap with [Main page actions should have save and publish labels](https://app.zenhub.com/workspace/o/silverstripe/silverstripe-cms/issues/2072)
 * Adding versioned to the object "fixes" the issue, but is not always feasible. For example, versioning a `Member` would case all kinds of edge cases.
 * While this issue is related to [allow $owns on non-versioned objects](https://github.com/silverstripe/silverstripe-framework/issues/7359#issuecomment-347748394), most concerns apply to $owns on versioned objects.
 * Many_many relationships cause ownership ambiguity, but in some cases it will still make sense to authors. Relationships to files are the most common example here.
 * Auto-publishing owned relationships can be dependant on the editing context (see [Sam's example](https://github.com/silverstripe/silverstripe-framework/issues/7359#issuecomment-346196784))

# Approach Brainstorming

 * Indicate versioned status on any relationship form fields
 * Indicate owned status on any relationship form fields
 * Show modal if the user is publishing any owned relationships, listing them to allow review
 * Allow opt-out of publishing owned relationships (and only publish direct fields). Either as [separate buttons](https://github.com/silverstripe/silverstripe-framework/issues/7359#issuecomment-346163366), or via a [checkbox](https://github.com/silverstripe/silverstripe-framework/issues/7359#issuecomment-347748394).
 * Allow nested comparison of draft with live record (incl. owned relationships)
 * Show "flattened" editing activity since last publish (incl. owned relationships)
 * Show info-level message alongside save/publish actions ("publishes all underlying content")
 * Change button label for non-versioned records (distinguish from "save" on a draft)

# Tasks

 * [] Design review

# Related

 * [Overview of changes in nested objects](https://github.com/silverstripe/silverstripe-versioned/issues/68)
 * [Show warning when unpublishing an object with owners](https://github.com/silverstripe/silverstripe-versioned/issues/26)

# Pull Requests
- [x] https://github.com/silverstripe/silverstripe-versioned/pull/107
- [x] https://github.com/silverstripe/silverstripe-admin/pull/418

**Comment by newleeland** [comment]
For unversioned objects owning version objects, there are 2 issues that can affect the user when updating (publishing/unpublishing/reverting/saving):
**Lack of preview** of everything being published/unpublished. The user may not be able to see all affected content on the screen where they are publishing/unpublishing/reverting/saving. Therefore, the need to add visibility for the user to see hidden objects that are being affected.
**Lack of visibility** for inter-page items. We need to give notice to the user if owned objects are used in other locations.

I think this story is more of a temporary solution, e.g. button labels changing, before we implement a full solution, i.e. activities window, showing what will be added/removed/changed on publish/delete.

**Comment by newleeland** [comment]
As a temporary option, we could look at relabelling options, however, to have full visibility we would need an activity feed like mechanism.

**Interim solution**
![screen shot 2017-12-06 at 10 31 55 am](https://user-images.githubusercontent.com/8085295/33633332-491d9a70-da75-11e7-882b-56db3449802e.png)

**Comment by clarkepaul** [comment]
Other text we are considering with the above:
<img width="614" alt="pasted_image_18_12_17__10_28_am" src="https://user-images.githubusercontent.com/555033/34084430-28ed678e-e3e5-11e7-9511-c6f20ba8b7da.png">

**Comment by tractorcow** [comment]
Also see https://github.com/silverstripe/silverstripe-versioned/issues/78 for archive / delete action considerations.

**Comment by newleeland** [comment]
## User Test Summary
There are large about of users (content authors/publisher/process managers) using "apply changes" for unversioned content and when unversioned content owned versioned content. While there were a large number of users using "Save" and "Publish", respectively, they were on used in separate cases. Not many users used "Save" for unversioned content together with using "Publish" for unversioned content that owned versioned draft content.

From the results of the user test as follows, https://docs.google.com/document/d/1OpWNjnkOchTYvCr7vLve1MslMXnzqBT_L6hceArPqmA/edit?usp=sharing

## Recommendations
### Option 1
This issue is an edge case, for the most part, we would expect user would know what they are saving/updating, 
- by default, everything gets updated and published
- There is an option to exclude versioned items, this placed out of the way, not cluttering up the screen.
- Change button name to "Apply Changes"

**Unversioned content only**
https://invis.io/NP79NDU4J#/274900127_Page_TinyMCE_States_Right_Top_2_Copy_5

**Unversioned owned version** https://invis.io/NP79NDU4J#/274900126_Page_TinyMCE_States_Right_Top_2_Copy_4

### Option 2
Similar to  the first option, this option places priority giving visibility of the ability to exclude versioned items.
![page_tinymce_states right top 2 copy 10](https://user-images.githubusercontent.com/8085295/35256208-94799f0c-0057-11e8-885c-a89c74894b03.png)

**Comment by tractorcow** [comment]
Looks good.

But don't forget "modified on draft" appear as "modified" so we may need to tweak the wording to include all change types.

**Comment by tractorcow** [comment]
@chillu let's discuss this at standup tomorrow.

**Comment by chillu** [comment]
Great work Jared! We've previously established that this use case is only really valid for unversioned content owning files/images (e.g. an unversioned office location owning office images). For every other use case we came up with, two alternatives applied:

1. Both the owner and owned relationship are versioned (e.g. a versioned office page owning versioned office images)
1. Both the owner and owned relationship are unversioned (e.g. an unversioned office location owning unversioned office managers).

Given that 10 people were "comfortable or "comfortable with notice" in scenario 2 (compared to 12 people "comfortable with options", I'd say we'll start with the MVP solution and only add a warning about "draft" content. An option to exclude draft content from publication can be split out into further work.

**Comment by clarkepaul** [comment]
Great to see data to inform decisions :)

**Comment by newleeland** [comment]
We can start with this notification.
![page_tinymce_states right top 2 copy 14](https://user-images.githubusercontent.com/8085295/35360138-926e9346-01c1-11e8-8dda-a6b04dcc88b5.png)
And progress to one with additional options as well
![page_tinymce_states right top 2 copy 4](https://user-images.githubusercontent.com/8085295/35360242-f601c4e6-01c1-11e8-9819-00ac59093226.png)

If both owner and ownee are versioned then, it would just be "save" and "publish"
If both owner and ownee are unversioned the it could just be "Apply changes"
It would be good to keep "Save" and "Publish" within Pages and Files, so that everything that is going to be made public is not scattered throughout the CMS
