### ISSUE TITLE
Unexpected behaviour with write without version

### ISSUE THREAD

**Issue by chrispenny** [silverstripe/silverstripe-versioned#85]
This may be a feature request, and not a bug.

# Scenario.

## 1) I save a `SiteTree` record to draft.

- The `SiteTree` table record is correctly updated. Changes can be seen in the edit form.
- A new record is created under `SiteTree_Versions` (version `2`).

## 2) Changes are made outside of the CMS edit form (for whatever reason) to the `Stage` record, and `writeWithoutVersion()` is called.

- The `SiteTree` table record is correctly updated. Changes can be seen in the edit form if you go back to view it.
- The current (version `2`) `SiteTree_Versions` record is incorrectly(?) untouched.

The current record in the `SiteTree` table and the corresponding record in the `SiteTree_Versions` table no longer match.

## 3) I save the same `SiteTree` record to draft again.

- The `SiteTree` table record is correctly updated. Changes can be seen in the edit form.
- A new record is created under `SiteTree_Versions` (version `3`).

## 4) I visit the history tab and revert to version `2`.

- The content seen is that of step **1** instead of step **2**.

# Desired outcome / feature request

The desired outcome (for me, at least) is that when I call `writeWithoutVersion`, the previous state of the Object (whatever that state was) is forgotten, and the new state silently takes it's place.

OR: I have a new way to achieve this, without manually running an `SQLUpdate` on the `_Versions` table.

# Live usage examples

We have a map picker that the authors use to select a lat/long. Unfortunately for us, there is additional data from a (potentially unreliable) external API that we need to add to the Object based on that lat/long.

Because we can't guarantee the availability of this external API, instead of fetching the data as part of the `write` action, we instead create an immediate queued job. This allows authors to freely save their Object even if the API is down, and it keeps our user expectations consistent.

The queued job goes and does it's thing, if it fails, it lets us know, if it doesn't fail, it saves the retrieved data against the Object and calls `writeWithoutVersion`. The idea being that the version of this Object that only had the lat/long is no longer relevant.

The author should not be able to revert back to the version of the Object that only had the lat/long once all of the required data have been retrieved and saved.

**Comment by chillu** [comment]
@tractorcow Could you work through this case please?

**Comment by tractorcow** [comment]
> The current record in the SiteTree table and the corresponding record in the SiteTree_Versions table no longer match.

Yeah because you are making a write that bypasses writing to the version history. `_Versions` table is meant to be add-only. If you save changes to stage with `writeWithoutVersion`, those changes won't be saved to the archive until the next write.

You aren't modifying the old version, you are creating a new version that's never versioned anywhere.

If you could modify the version history, that would defeat the purpose of keeping the history, since it would no longer be an accurate representation of the history.

> The idea being that the version of this Object that only had the lat/long is no longer relevant.

I would argue here that it's still a valid representation of the history, and shouldn't be discarded simply because the value was since updated.

I would recommend to write normally in your case and have an extra version record.

> The author should not be able to revert back to the version of the Object that only had the lat/long once all of the required data have been retrieved and saved.

Then you need an additional query condition that filters out those records from the history tab, or otherwise resolve this by per-version permissions. I can probably help you with this offline.
