### ISSUE TITLE
Should ChangeSet::publish()/ChangeSetItem::publish() check canPublish()?

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-versioned#89]
Raised on Slack, I’m not sure it makes much sense to check this inside the `publish()` methods - it should be possible to trigger the action programatically, regardless of who is logged in. I’d liken it to checking `canEdit()` inside `DataObject::write()`.

IMO it’s the responsibility of the code implementing `ChangeSet::publish()` (or `ChangeSetItem::publish()`) to handle checking permissions. At least that’s how we’ve traditionally handled things :)

---

Edit: I’m advocating removing these checks:
- https://github.com/silverstripe/silverstripe-versioned/blob/1.0.1/src/ChangeSet.php#L133-L135
- https://github.com/silverstripe/silverstripe-versioned/blob/1.0.1/src/ChangeSetItem.php#L242-L244

**Comment by robbieaverill** [comment]
Yeah, it's be nice to assume that any code implementing some logic saying "publish something" should first check permissions for it, but it's unlikely to be followed in practice.

If this were implemented into `ChangeSet::publish` then you'd also encourage user code to add the checks in their own code in order to handle permission failure messages in a custom way, for example.

**Comment by kinglozzer** [comment]
> If this were implemented into `ChangeSet::publish` then you'd also encourage user code to add the checks in their own code in order to handle permission failure messages in a custom way, for example.

Sorry, my original comment wasn’t very clear! Status-quo is that `ChangeSet::publish()` _does_ check permissions and throw an exception if they’re not met, I’m advocating removing that 😁

**Comment by robbieaverill** [comment]
That’ll teach me for skim reading!

**Comment by dhensby** [comment]
I think I agree

**Comment by zanderwar** [comment]
These lines should also be removed:

* https://github.com/silverstripe/silverstripe-versioned/blob/1.0.1/src/Versioned.php#L1495-L1497

**Comment by tractorcow** [comment]
See my comment at https://github.com/silverstripe/silverstripe-framework/issues/7837#issuecomment-363567507

**Comment by kinglozzer** [comment]
I still don’t think these permission checks make sense “inside” these actions - it should be up to the implementing code to perform any checks. We don’t perform these checks in 3.x, nor do we check `canWrite()` in `DataObject::write()` in 4.x...

**Comment by tractorcow** [comment]
I think we need to weigh the practicality of developer-explicitly invoked commands vs the security of users performing unauthorised actions on objects. In the past these extra can* methods acted as a security layer against gaps in usercode permission checking.

In most sites, such checks are more an afterthought than a standard practice. :)

I feel like it would be safer to provide more tools for developers to temporarily elevate the permissions of the current process.

The analogy is logging in as root to a remote server rather than using `sudo` on specific commands, which is a non-recommended practice.

**Comment by kinglozzer** [comment]
Closed in https://github.com/silverstripe/silverstripe-versioned/pull/113
