### ISSUE TITLE
History Viewer: Revert

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-versioned#95]
# Acceptance Criteria

 * I can revert to an earlier version of the record I'm viewing
 * The feature works for pages and other versioned records
 * A revert will put the record into draft mode
 * I get clear indication that I need to publish the record for the revert to take effect
 * If the history viewer is shown alongside a preview panel, the preview panel shows the reverted version after a revert has been actioned

# Notes

 * Track design time against ORB-175 Pattern Library
 * Designs at https://invis.io/FJEHOLLEN#/263513634_Pages_History_Tab
 * GraphQL mutation support has already been added via `copyToStage` in https://github.com/silverstripe/silverstripe-graphql/issues/30
 * Mostly UI-focused card, does not concern itself with cascading reverts, see https://app.zenhub.com/workspace/o/silverstripe/silverstripe-versioned/issues/94

## Pull requests

- [x] https://github.com/silverstripe/silverstripe-admin/pull/505
- [x] https://github.com/silverstripe/silverstripe-cms/pull/2158
- [x] https://github.com/dnadesign/silverstripe-elemental/pull/230
- [x] https://github.com/silverstripe/silverstripe-versioned-admin/pull/13

**Comment by chillu** [comment]
> I get clear instructions that I need to publish the record for the revert to take effect

@clarkepaul That's currently not part of the designs, I just made up that AC. Do you think it's necessary? It can be counter intuitive to CMS authors that a revert requires a separate user action (publish) to take effect. Maybe that's communicate clearly enough by adding a "draft" label already - although I'm not sure that's the case without a page refresh?

**Comment by clarkepaul** [comment]
It personally doesn't feel too disjointed when reverting a page with the "save" action showing as "saved", we should also soon have a status (eg Draft) next to the page title which will re-enforce the page state as well. The other option would be to use a in-page alert instead of the temporary right-top notification so that we can elaborate on the page status. Would you mind if we change that AC to "I get a clear **indication** that I need to publish the record for the revert to take effect" as showing a draft status should suffice IMHO.

I'll add this to a list of possible things we can test (hoping to bundle a bunch of smaller tests together).

**Comment by chillu** [comment]
I've changed it to indication, which seems to be already present in the current UI (showing "saved" label on button, with a "draft" label)

**Comment by robbieaverill** [comment]
Primary PRs for the CMS reverting are added to the ticket description, I'll be finishing off elemental tomorrow

**Comment by robbieaverill** [comment]
All merged 🎉
