### ISSUE TITLE
History Viewer: Preview a version (for pages)

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-versioned#99]
# Acceptance Criteria

 * I can preview a selected version if a preview panel exists for this page

# Notes

 * Track design time against ORB-175 Pattern Library
 * Designs at https://projects.invisionapp.com/share/FJEHOLLEN#/screens/263513634_Pages_History_Tab
 * Designs only show this for pages at the moment, which would include content blocks once we implement/validate https://app.zenhub.com/workspace/o/silverstripe/silverstripe-versioned/issues/93. There's currently no way to get a preview when you're looking at a particular content block

## Pull requests

- [x] https://github.com/silverstripe/silverstripe-admin/pull/478
- [x] https://github.com/silverstripe/silverstripe-versioned-admin/pull/5 (previous ticket, needs merging  and following PR to be rebased)
- [x] https://github.com/silverstripe/silverstripe-cms/pull/2142
- [ ] https://github.com/silverstripe/silverstripe-versioned-admin/pull/8

**Comment by robbieaverill** [comment]
Resolving this issue will also include https://github.com/silverstripe/silverstripe-versioned-admin/issues/3

**Comment by robbieaverill** [comment]
I've just spoken to @clarkepaul about the actions in the preview panel. Ideally we'll be able to move across the screen size selector and the split/preview/edit mode toggle from the existing CMS history area:

![image](https://user-images.githubusercontent.com/5170590/38348067-c4c1e910-38f3-11e8-8a2f-71e3041e2eb5.png)
![image](https://user-images.githubusercontent.com/5170590/38348069-c9ead1a4-38f3-11e8-803b-f0a3bfa713d8.png)

These two features will need to be created as React components, since I'm hoping to use the Preview React component from silverstripe/admin for this work.

The alternative is to _not_ use the React-based preview component and continue to use the legacy CMS preview functionality with custom hooks to update it added into the React component for HistoryViewer.

Would be good to get some thoughts on this from you @chillu when you have a minute =)
